In [4]:
import pandas as pd
import numpy as np
df_red = pd.read_csv('winequality-red.csv', sep=";")
df_white = pd.read_csv('winequality-white.csv', sep=";")

In [5]:
df_red.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [6]:
df_white.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

In [7]:
df_red.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
fixed acidity,1599.0,8.319637,1.741096,4.60000,7.1000,7.90000,9.200000,15.90000
volatile acidity,1599.0,0.527821,0.179060,0.12000,0.3900,0.52000,0.640000,1.58000
citric acid,1599.0,0.270976,0.194801,0.00000,0.0900,0.26000,0.420000,1.00000
residual sugar,1599.0,2.538806,1.409928,0.90000,1.9000,2.20000,2.600000,15.50000
chlorides,1599.0,0.087467,0.047065,0.01200,0.0700,0.07900,0.090000,0.61100
free sulfur dioxide,1599.0,15.874922,10.460157,1.00000,7.0000,14.00000,21.000000,72.00000
total sulfur dioxide,1599.0,46.467792,32.895324,6.00000,22.0000,38.00000,62.000000,289.00000
density,1599.0,0.996747,0.001887,0.99007,0.9956,0.99675,0.997835,1.00369
pH,1599.0,3.311113,0.154386,2.74000,3.2100,3.31000,3.400000,4.01000
sulphates,1599.0,0.658149,0.169507,0.33000,0.5500,0.62000,0.730000,2.00000
alcohol,1599.0,10.422983,1.065668,8.40000,9.5000,10.20000,11.100000,14.90000
quality,1599.0,5.636023,0.807569,3.00000,5.0000,6.00000,6.000000,8.00000

In [8]:
df_white.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
fixed acidity,4898.0,6.854788,0.843868,3.80000,6.300000,6.80000,7.3000,14.20000
volatile acidity,4898.0,0.278241,0.100795,0.08000,0.210000,0.26000,0.3200,1.10000
citric acid,4898.0,0.334192,0.121020,0.00000,0.270000,0.32000,0.3900,1.66000
residual sugar,4898.0,6.391415,5.072058,0.60000,1.700000,5.20000,9.9000,65.80000
chlorides,4898.0,0.045772,0.021848,0.00900,0.036000,0.04300,0.0500,0.34600
free sulfur dioxide,4898.0,35.308085,17.007137,2.00000,23.000000,34.00000,46.0000,289.00000
total sulfur dioxide,4898.0,138.360657,42.498065,9.00000,108.000000,134.00000,167.0000,440.00000
density,4898.0,0.994027,0.002991,0.98711,0.991723,0.99374,0.9961,1.03898
pH,4898.0,3.188267,0.151001,2.72000,3.090000,3.18000,3.2800,3.82000
sulphates,4898.0,0.489847,0.114126,0.22000,0.410000,0.47000,0.5500,1.08000
alcohol,4898.0,10.514267,1.230621,8.00000,9.500000,10.40000,11.4000,14.20000
quality,4898.0,5.877909,0.885639,3.00000,5.000000,6.00000,6.0000,9.00000

For red wine, Assing input (X) and output (y);
              Split training set and test set;
              Normalize X data (on training set).

In [9]:
y = (df_red['quality'].values > 6)
X = df_red.iloc[:,0:-1]
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = \
    train_test_split(X, y, test_size=0.3, random_state=0)

from sklearn.preprocessing import StandardScaler
stdsc = StandardScaler()
X_train_std = stdsc.fit_transform(X_train)
X_test_std = stdsc.transform(X_test)
pd.DataFrame(X_train_std).describe().transpose()

,count,mean,std,min,25%,50%,75%,max
0,1119.0,-1.271945e-16,1.000447,-2.090941,-0.712549,-0.253085,0.550977,4.341555
1,1119.0,-1.214399e-16,1.000447,-2.214153,-0.757544,-0.056214,0.591167,5.662322
2,1119.0,-2.622765e-16,1.000447,-1.396757,-0.934734,-0.062025,0.759348,3.736827
3,1119.0,2.115277e-16,1.000447,-1.108115,-0.438669,-0.237836,0.029943,8.665794
4,1119.0,-1.587450e-18,1.000447,-1.527181,-0.356857,-0.175255,0.046703,10.559442
5,1119.0,1.438627e-16,1.000447,-1.419711,-0.767974,-0.209341,0.535501,5.190770
6,1119.0,1.230274e-17,1.000447,-1.210217,-0.743039,-0.275861,0.454105,7.052999
7,1119.0,-5.975193e-14,1.000447,-3.520329,-0.608117,-0.018302,0.582045,3.652243
8,1119.0,1.005551e-15,1.000447,-3.669365,-0.638236,0.006686,0.587115,4.521134
9,1119.0,-3.551920e-17,1.000447,-1.626274,-0.618757,-0.226944,0.388761,7.497358
10,1119.0,-8.838129e-16,1.000447,-1.888447,-0.854927,-0.291189,0.585737,4.218717

For white wine, Assing input (N) and output (m);
              Split training set and test set;
              Normalize N data (on training set).

In [10]:
m = (df_white['quality'].values > 6)
N = df_white.iloc[:,0:-1]
from sklearn.cross_validation import train_test_split
N_train, N_test, m_train, m_test = \
    train_test_split(N, m, test_size=0.3, random_state=0)

from sklearn.preprocessing import StandardScaler
stdsc = StandardScaler()
N_train_std = stdsc.fit_transform(N_train)
N_test_std = stdsc.transform(N_test)
pd.DataFrame(N_train_std).describe().transpose()

,count,mean,std,min,25%,50%,75%,max
0,3428.0,6.042748e-16,1.000146,-3.679287,-0.670241,-0.068432,0.653739,5.949660
1,3428.0,1.789053e-16,1.000146,-1.972843,-0.684689,-0.189246,0.405287,8.134207
2,3428.0,-1.854353e-16,1.000146,-2.791145,-0.523537,-0.187595,0.400303,11.150443
3,3428.0,-2.303033e-16,1.000146,-1.149586,-0.929125,-0.247702,0.674223,5.063389
4,3428.0,-2.517353e-16,1.000146,-1.664892,-0.447283,-0.131606,0.184070,13.532671
5,3428.0,-1.093382e-16,1.000146,-1.959411,-0.726534,-0.080741,0.623760,14.889912
6,3428.0,2.027015e-17,1.000146,-3.056039,-0.696517,-0.106636,0.695601,7.113503
7,3428.0,-3.177000e-14,1.000146,-2.337267,-0.776760,-0.096801,0.719151,5.546864
8,3428.0,1.014423e-15,1.000146,-2.959341,-0.717246,-0.057807,0.601633,4.096662
9,3428.0,-3.476410e-16,1.000146,-2.326912,-0.693743,-0.092049,0.509644,5.065325
10,3428.0,2.983643e-16,1.000146,-1.728126,-0.835604,-0.105358,0.706025,2.977900

Apply normilization, PCA (first 2 components) and logistic regression on red wine.

In [11]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
pipe_lr = Pipeline([('scl', StandardScaler()),
                    ('pca', PCA(n_components=2)),
                    ('clf', LogisticRegression(random_state=1))])
pipe_lr.fit(X_train, y_train)
print('Test Accuracy: %.3f' % pipe_lr.score(X_test, y_test))
y_pred = pipe_lr.predict(X_test)

Test Accuracy: 0.892

Apply normilization, PCA (first 2 components) and logistic regression on white wine.

In [12]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
pipe_lr = Pipeline([('scl', StandardScaler()),
                    ('pca', PCA(n_components=2)),
                    ('clf', LogisticRegression(random_state=1))])
pipe_lr.fit(N_train, m_train)
print('Test Accuracy: %.3f' % pipe_lr.score(N_test, m_test))
m_pred = pipe_lr.predict(N_test)

Test Accuracy: 0.784

Apply Support Vector Machine with RBF kernel on red wine.

In [13]:
from sklearn.svm import SVC

pipe_lr = Pipeline([('scl', StandardScaler()),
                    ('pca', PCA(n_components=2)),
                    ('svm', SVC(kernel='rbf', random_state=0, gamma=0.20, C=5.0))])

pipe_lr.fit(X_train, y_train)
print('Test Accuracy: %.3f' % pipe_lr.score(X_test, y_test))
y_pred = pipe_lr.predict(X_test)

Test Accuracy: 0.894

Apply Support Vector Machine with RBF kernel on white wine.

In [14]:
from sklearn.svm import SVC

pipe_lr = Pipeline([('scl', StandardScaler()),
                    ('pca', PCA(n_components=2)),
                    ('svm', SVC(kernel='rbf', random_state=0, gamma=0.20, C=5.0))])

pipe_lr.fit(N_train, m_train)
print('Test Accuracy: %.3f' % pipe_lr.score(N_test, m_test))
m_pred = pipe_lr.predict(N_test)

Test Accuracy: 0.784

Linear Regression model of red wine and confusion matrix.

In [15]:
import sklearn.linear_model as skl_lm

y = df_red['quality']

X_train, X_test, y_train, y_test = \
    train_test_split(X, y, test_size=0.3, random_state=0)

regr=skl_lm.LinearRegression()

regr.fit(X_train,y_train)

y_pred =regr.predict(X_test)

y_pred = (y_pred > 5.63)
y_test = (y_test > 5.63)

In [16]:
from sklearn.metrics import confusion_matrix
outcome = confusion_matrix(y_true=y_test, y_pred=y_pred)
print(outcome)

result=np.matrix(outcome)
ERR=(result[0,1]+result[1,0])/(result[0,0]+result[0,1]+result[1,0]+result[1,1])
ERR

[[173  53]
 [ 78 176]]

0.27291666666666664

Linear Regression model of white wine and confusion matrix.

In [17]:
import sklearn.linear_model as skl_lm

m = df_white['quality']

N_train, N_test, m_train, m_test = \
    train_test_split(N, m, test_size=0.3, random_state=0)

regr=skl_lm.LinearRegression()

regr.fit(N_train,m_train)

m_pred =regr.predict(N_test)

m_pred = (m_pred > 6)
m_test = (m_test > 6)

In [18]:
from sklearn.metrics import confusion_matrix
outcome = confusion_matrix(y_true=m_test, y_pred=m_pred)
print(outcome)

result=np.matrix(outcome)
ERR=(result[0,1]+result[1,0])/(result[0,0]+result[0,1]+result[1,0]+result[1,1])
ERR

[[790 367]
 [ 82 231]]

0.30544217687074832